<?php
// Variables
return [
  "creatorName" => "GMIM Betania Tingkulu",
  "creatorUrl" => "#",
  "templateName" => "SIG GMIM",
  "templateSuffix" => "Betania Tingkulu",
  "templateVersion" => "1.0.0",
  "templateFree" => true,
  "templateDescription" => "Sistem Informasi Geografis Jemaat GMIM Betania Tingkulu",
  "templateKeyword" => "sig, gmim, jemaat, gereja, betania tingkulu",
  "licenseUrl" => "#",
  "livePreview" => "#",
  "productPage" => "#",
  "support" => "#",
  "adminTemplates" => "#",
  "bootstrapDashboard" => "#",
  "ogTitle" => "SIG GMIM Betania Tingkulu",
  "ogImage" => "",
  "ogType" => "website",
  "documentation" => "#",
  "repository" => "#",
  "gitRepo" => "#",
  "gitRepoAccess" => "#",
  "githubFreeUrl" => "#",
  "facebookUrl" => "#",
  "twitterUrl" => "#",
  "githubUrl" => "#",
  "dribbbleUrl" => "#",
  "instagramUrl" => "#"
];
